version: 0.4.1-{branch}+{build}
image: Visual Studio 2017

install:
- choco install gitversion.portable -pre -y
- cmd: dotnet tool install --global dotnet-sonarscanner
- ps: .\build.ps1 InitProject

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
- ps: .\build.ps1 clean -configuration Release
- ps: .\build.ps1 artifacts -configuration Release -codeanalysis true

artifacts:
- path: 'artifacts\*.zip'